config/routes.rb
Rails.application.routes.draw do
  get 'pages/contacts'

  get 'pages/about'

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root                       to: "auto_show#index"
  get 'auto_shows/:href_id', to: "auto_show#show"
  get 'brands/:href_id',     to: "auto_show#index_of_brand"
  get 'best',                to: "auto_show#index_of_best"
  get 'worst',               to: "auto_show#index_of_worst"
  get 'most_discussed',      to: "auto_show#index_of_discussed"

  get 'last_reviews', to: "reviews#index_of_last"
  resources :reviews, only: [:index, :show, :new, :create]
  resources :feedbacks, only: [:new, :create]


  get 'about',    to: "pages#about"
  get 'contacts', to: "pages#contacts"

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/auto_show.rb
class AutoShow < ApplicationRecord
  mount_uploader :logo, LogoUploader
  mount_uploader :picture, PictureUploader

  serialize :brands, Array
  attr_accessor   :brands_raw

  has_many :reviews

  def brands_raw
    self.brands.join("\n") unless self.brands.blank?
  end

  def brands_raw=(values)
    self.brands = []
    self.brands=values.split("\n")
  end

  def brands_names_row
    Brand.select(:name).where(id: brands).map{|b| b.name}
  end

  def brands_obj
    Brand.where(id: brands)
  end

  def brands_names
    brands_names_row.join(', ')
  end

  def address_for_google
    address.gsub(/([.,:])\s/,'\1').gsub(/\s/,'+')
  end

  scope :best, -> {
    limit(9)
        .where('(select count(*) from reviews where auto_show_id = auto_shows.id)>0')
        .order('(select avg(value) from reviews where auto_show_id = auto_shows.id) DESC')
  }
  scope :worst,  -> {
    limit(9)
        .where('(select count(*) from reviews where auto_show_id = auto_shows.id)>0')
        .order('(select avg(value) from reviews where auto_show_id = auto_shows.id) ASC')
  }
  scope :discussed, lambda {limit(9).order('(select count(*) from reviews where auto_show_id = auto_shows.id) DESC')}
  scope :brand,     lambda {|brand_id| where("brands like '%#{brand_id}%'")
                                          .order('(select avg(value) from reviews where auto_show_id = auto_shows.id) DESC')}
  scope :ordered,   lambda {order(:name)}

  def rating
    self.reviews.average('value').to_f.round
  end
end

app/models/brand.rb
class Brand < ApplicationRecord
end

app/models/catalog.rb
class Catalog < ApplicationRecord
  def title_for_brand(brand)
    title.gsub('%{brand}', brand)
  end
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, :to => :data

  validates_presence_of :data
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, :mount_on => :data_file_name

  def url_content
    url(:content)
  end
end

app/models/feedback.rb
class Feedback < ApplicationRecord
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :auto_show
  mount_uploader :photo, PhotoUploader

  scope :last_registered, -> {where 'created_at > ?', Time.now - (86400 * 7) }
  scope :ordered, -> {order :created_at}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :set_common

  def not_found
    raise ActionController::RoutingError.new('Not Found')
  end

  def respond_modal_with(*args, &blk)
    options = args.extract_options!
    options[:responder] = ModalResponder
    respond_with *args, options, &blk
  end

  private

  def set_common
    unless self.class.parent == Admin # Только если не админка
      @brands = Brand.all
      @popular = AutoShow.where(popular: true).all
    end
  end
end

app/controllers/auto_show_controller.rb
class AutoShowController < ApplicationController

  before_action :init_review, only: [:index, :index_of_brand, :index_of_best, :index_of_worst, :index_of_discussed, :show]

  def index
    @auto_shows=AutoShow.ordered
    @catalog=Catalog.find_by_href_id('best')
    add_paginate
  end

  def index_of_brand
    @brand = (Brand.find_by_href_id(params[:href_id]) or not_found)
    @auto_shows=AutoShow.brand(@brand.id)
    @catalog=Catalog.find_by_href_id('brands')
    add_paginate
    render 'index'
  end

  def index_of_best
    @auto_shows=AutoShow.best
    @catalog=Catalog.find_by_href_id('best')
    add_paginate
    render 'index'
  end

  def index_of_worst
    @auto_shows=AutoShow.worst
    @catalog=Catalog.find_by_href_id('worst')
    add_paginate
    render 'index'
  end

  def index_of_discussed
    @auto_shows=AutoShow.discussed
    @catalog=Catalog.find_by_href_id('discussed')
    add_paginate
    render 'index'
  end

  def show
    @auto_show = (AutoShow.find_by_href_id(params[:href_id]) or not_found)
  end

  def init_review
    @review = Review.new
  end

  private

  def add_paginate
    @pages = (@auto_shows.count/9.0).ceil
    @page = (params[:page].to_i if params[:page]) || 1
    @page = @pages if @page > @pages
    @auto_shows=@auto_shows.limit(9).offset(9*@page-9)
  end

end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  respond_to :html, :json

  def new
    @feedback = Feedback.new
    respond_modal_with @feedback
  end

  def create
    if (f = params[:feedback])
      @feedback = Feedback.new(
          name:    f[:name],
          email:   f[:email],
          message: f[:message]
      )
      @feedback.save
    end
    respond_modal_with @feedback, location: root_path
  end
end

app/controllers/modal_responder.rb
class ModalResponder < ActionController::Responder
  cattr_accessor :modal_layout
  self.modal_layout = 'modal'

  def render(*args)
    options = args.extract_options!
    if request.xhr?
      options.merge! layout: modal_layout
    end
    controller.render *args, options
  end

  def default_render(*args)
    render(*args)
  end

  def redirect_to(options)
    if request.xhr?
      head :ok, location: controller.url_for(options)
    else
      controller.redirect_to(options)
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def contacts
    @feedback = Feedback.new
  end

  def about
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  respond_to :html, :json

  def index
    @reviews = Review.ordered.all
  end

  def index_of_last
    @reviews = Review.last_registered.ordered.all
    render 'index'
  end

  def show
  end

  def new
    @review = Review.new
    respond_modal_with @review
  end

  def create
    if (f = params[:review])
      @review = Review.new(
          auto_show_id:f[:auto_show],
          name:        f[:name],
          email:       f[:email],
          description: f[:description],
          value:       f[:value],
          photo:       f[:photo])
      @review.save
    end
    respond_modal_with @review, location: root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auto_show_helper.rb
module AutoShowHelper
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/review_helper.rb
module ReviewHelper
end

app/views/blocks/_footer.slim
.cols.col-12.main-page
  .footer
    .content
      .cols.col-5.footer-left
        .logo-footer
        .copy
          p 2016 домен.рф
          span
            | Использование материалов сайта возможно исключительно
            | с разрешения владельца
      .cols.col-7.footer-right
        .footer-menu
          li.link-bl  =link_to "Каталог", root_path
          li.link-bl  =link_to "О сайте", about_path
          li.link-bl  =link_to "Контакты", contacts_path
          li          =link_to "Топ худших", worst_path
          li          =link_to "Самые обсуждаемые", most_discussed_path
          li          =link_to "Последние мнения", last_reviews_path
          li          =link_to "Реальные отзывы", reviews_path
        .footer-brend
          =render 'brands/list'

app/views/blocks/_header.html.slim
.container
  .header.clearfix
    .cols.col-6
      .logo
        = link_to root_path do
          =image_tag 'logo.png', alt: "Рейтинг автосалонов Москвы"
        = link_to root_path do
          span Рейтинг автосалонов Москвы
        = link_to root_path do
          p Честно и объективно, от покупателей
          a.front href="/"
      .stars-top
        =image_tag "top-stars.png"
    .cols.col-6
      .top-right
        .auto-salon
          span Автосалоны по маркам:
          =render 'brands/list'
        .top-auto-salon
          span Популярные:
          - @popular.each do |item|
            =link_to "Автосалон #{item.name}", "auto_shows/#{item.href_id}"
        .review-top
          li.first
            = link_to 'Оставить отзыв', new_review_path, data: { modal: true }
          li.second
            = link_to  'Связь с администрацией', new_feedback_path, data: { modal: true }

app/views/blocks/_menu.slim
.navigation.clearfix
  .row
    nav.pushy.pushy-left
      ul
        li.pushy-link
          =link_to "Топ лучших", best_path
        li.pushy-link
          = link_to "Каталог", root_path
        li.pushy-link
          = link_to "О сайте", about_path
        li.pushy-link
          = link_to "Контакты", contacts_path
        li.pushy-link
          =link_to "Топ худших", worst_path
          span 9
        li.pushy-link
          =link_to "Самые обсуждаемые", most_discussed_path
          span 9
        li.pushy-link
          =link_to "Последние мнения", last_reviews_path
          span 34
        li.pushy-link
          =link_to "Реальные отзывы", reviews_path
          span =Review.count



    .cols.col-5.left-menu
      .menu-btn
        =image_tag "menu.png"
          span Меню
      .red-left
      .top-button
        =link_to "Топ лучших", best_path
    .cols.col-7.right-menu
      .first-menu
        li.link-first
          =link_to root_path do
            span Каталог
        li.link-second
          =link_to about_path do
            span О сайте
        li.link-third
          =link_to contacts_path do
            span Контакты
      .second-menu
        li
          =link_to "Топ худших", worst_path
          span 9
        li
          =link_to "Самые обсуждаемые", most_discussed_path
          span 9
        li
          =link_to "Последние мнения", last_reviews_path
          span 34
        li.end-s
          =link_to "Реальные отзывы", reviews_path
          span =Review.count

.site-overlay

app/views/blocks/_pages_menu.slim
.block-nav
  .nav-page
    - pth = request.env['PATH_INFO']
    = link_to('', pth, class:'arrows-pre') if @page>1
    = link_to('', pth, class: 'arrow-pre') if @page==2
    = link_to('', pth+"?page=#{@page-1}", class: 'arrow-pre') if @page>2
    .links-nav
      - f=false
      - @pages.times do |index|
        - i=index+1
        - if [1,@pages, *((@page-1)..(@page+1))].include? i
          = link_to i, pth+"?page=#{i}", class: "#{'active' if @page==i }"
          - f=true
        - else
          - if f
            span.dot
          - f=false
    = link_to('', pth+"?page=#{@page+1}", class: 'arrow-next')  if @page < @pages
    = link_to('', pth+"?page=#{@pages}",  class: 'arrows-next') if @page < @pages

app/views/layouts/_embed_styles.html.erb
<style>

  html {
    font-family: sans-serif;
    -ms-text-size-adjust: 100%;
    -webkit-text-size-adjust: 100%;
  }

  body {
    margin: 0;
  }

  nav {
    display: block;
  }

  a {
    background-color: transparent;
  }

  h1 {
    font-size: 2em;
    margin: 0.67em 0;
  }

  img {
    border: 0;
  }

  input {
    color: inherit;
    font: inherit;
    margin: 0;
  }

  input::-moz-focus-inner {
    border: 0;
    padding: 0;
  }

  input {
    line-height: normal;
  }

  * {
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
    box-sizing: border-box;
  }

  *:before,
  *:after {
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
    box-sizing: border-box;
  }

  html {
    font-size: 10px;
  }

  body {
    font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
    font-size: 14px;
    line-height: 1.42857143;
    color: #333333;
    background-color: #ffffff;
  }

  input {
    font-family: inherit;
    font-size: inherit;
    line-height: inherit;
  }

  a {
    color: #337ab7;
    text-decoration: none;
  }

  img {
    vertical-align: middle;
  }

  .clearfix:before,
  .clearfix:after {
    content: " ";
    display: table;
  }

  .clearfix:after {
    clear: both;
  }

  .alert {
    text-shadow: 0 1px 0 rgba(255,255,255,0.2);
    -webkit-box-shadow: inset 0 1px 0 rgba(255,255,255,0.25),0 1px 2px rgba(0,0,0,0.05);
    box-shadow: inset 0 1px 0 rgba(255,255,255,0.25),0 1px 2px rgba(0,0,0,0.05);
  }

  .pushy {
    position: fixed;
    width: 200px;
    height: 100%;
    top: 0;
    z-index: 9999;
    background: #191918;
    overflow: auto;
    visibility: hidden;
    -webkit-overflow-scrolling: touch;
  }

  .pushy a {
    display: block;
    color: #b3b3b1;
    padding: 15px 30px;
    text-decoration: none;
    outline: 0;
  }

  .pushy ul:first-child {
    margin-top: 10px;
  }

  .pushy.pushy-left {
    left: 0;
  }

  .pushy-left {
    -webkit-transform: translate3d(-200px, 0, 0);
    -ms-transform: translate3d(-200px, 0, 0);
    transform: translate3d(-200px, 0, 0);
  }



  .site-overlay {
    display: none;
  }

  .container {
    width: 100%;
  }

  .col-5 {
    width: 41.66665%;
  }

  .col-7 {
    width: 58.33333%;
  }

  .col-12 {
    width: 100%;
  }

  .row:after {
    content: " ";
    display: block;
    float: none;
    clear: both;
  }

  h1,
  h2,
  h3 {
    font-weight: 400;
  }

  .row {
    width: 1170px;
    margin: 0 auto;
  }

  .content {
    width: 1170px;
    margin: 0 auto;
    padding: 10px 0;
  }

  h2 {
    font-size: 18px;
    padding: 10px 0;
  }

  .preview {
    font-size: 14px;
    padding: 25px 0;
  }

  h1 {
    font-size: 24px;
    text-transform: uppercase;
    padding: 10px 0 20px;
  }

  .catalog-item {
    max-width: 340px;
    position: relative;
    overflow: visible;
    float: left;
    margin-top: 40px;
    margin-left: 70px;
  }

  .menu-btn img {
    width: 24px;
  }

  .top-button {
    float: left;
    background-image: url(/assets/btn-bg-8b1862a8cabaab7db15cb78b97b462ee250c14ace5e64ba6a25d35dee6915d32.png);
    background-position: 10px 150px;
    width: 240px;
    border-radius: 0 0 5px 5px;
    height: 135px;
    margin-top: -65px;
    position: relative;
    margin-left: 60px;
  }

  li.first {
    background-image: url(/assets/icon-msg-e64dc00a5887688752cfeb8f6fc1dafeb6d3d078d054d1370dc2d269d6f2733c.png);
    background-repeat: no-repeat;
    background-position: 0 -1px;
  }

  li.second {
    background-image: url(/assets/icon-admin-2bb2f53ea9334f7314eb88b30dfc610aaab25b884b1a285ec29a094b3cb95db9.png);
    background-repeat: no-repeat;
    background-position: 2px 2px;
  }

  .logo-grid {
    max-width: 150px;
    float: right;
    max-height: 40px;
  }

  .catalog-item h3 {
    float: left;
    color: #2897c0;
    font-size: 12px;
    text-transform: uppercase;
    text-decoration: underline;
    line-height: 40px;
    overflow: hidden;
    max-width: 180px;
    white-space: nowrap;
    text-overflow: ellipsis;
  }

  .rating {
    color: #fff;
    position: relative;
    width: 110px;
    height: 130px;
    margin-top: -88px;
    margin-left: 15px;
    font-size: 24px;
    text-align: center;
    background-repeat: no-repeat;
    background-position: 0 110px;
    float: left;
    z-index: 8;
  }

  .rating p {
    text-transform: uppercase;
    font-size: 12px;
    line-height: 40px;
  }

  .rating span {
    font-size: 36px;
    padding: 0 3px;
  }

  .rewiews-grid {
    position: absolute;
    right: 0;
    bottom: 15px;
  }

  .rewiews-grid span {
    font-size: 18px;
    color: #1c95c3;
    text-decoration: underline;
    margin-left: 3px;
  }

  .catalog-grid {
    margin-left: -70px;
  }

  .grade0 {
    background-color: #252525;
    background-image: url(/assets/star_0-d20cb49cc2981fcb4983524bdff554055464db7f3943295f7eb7519d57fd8fbc.png);
  }

  .grade2 {
    background-color: #f7420a;
    background-image: url(/assets/star_2-961d5d9c012904a12b49f46245f91c02b9e6baa5c341735f8d5d4b70ea63072d.png);
  }

  .rating-shadow {
    position: absolute;
    left: 92px;
    bottom: 20px;
    width: 40px;
    height: 22px;
    background: #460f0c;
    -webkit-transform: skew(-35deg);
    -moz-transform: skew(-35deg);
    -o-transform: skew(-35deg);
    transform: skew(-35deg);
    z-index: 2;
  }

  .menu-btn {
    display: none;
  }

  .foto-grid img {
    height: 222px;
  }

  @media screen and (max-width: 640px) {
    .container {
      overflow: hidden;
    }

    .row {
      width: 100%;
    }

    .header {
      width: 100%;
      padding: 0 10px;
    }

    .col-6 {
      width: 100% !important;
    }

    .stars-top {
      display: none;
    }

    .auto-salon {
      display: none;
    }

    .red-left,
    .cols.col-7.right-menu,
    .top-button {
      display: none;
    }

    .catalog-grid {
      max-width: 340px;
      margin: 0 auto;
    }

    .catalog-item {
      margin-left: 0;
      margin-bottom: 30px;
    }

    .menu-btn {
      display: block;
      background-color: #e12e21;
      padding: 20px;
      color: #fff;
      font-size: 20px;
      font-weight: 600;
    }

    .review-top li a {
      padding-top: 28px;
      font-size: 14px;
    }

    .catalog-item h3 {
      font-size: 16px;
      margin-bottom: 15px;
      padding-top: 5px;
    }

    .review-top {
      margin-top: 30px;
      position: relative;
    }

    .auto-salon span,
    .top-auto-salon span {
      font-size: 14px;
      font-weight: 600;
      text-transform: uppercase;
    }

    .review-top li a {
      height: 40px;
      border: none;
      background-color: #ddd;
      padding: 10px 15px 10px 10px;
      border-radius: 0 5px 5px 0;
      font-size: 14px;
      text-transform: none;
      font-weight: 600;
    }

    .review-top li {
      display: block;
      width: 100%;
    }

    .second-menu li a {
      font-size: 15px;
      padding: 10px 0;
    }

    li.first {
      background-position: 10px 11px;
      padding: 10px;
      padding-top: 0;
    }

    li.second {
      background-position: 10px 13px;
      padding: 10px;
      padding-top: 0;
    }

    li.second:before,
    li.first:before {
      content: " ";
      position: absolute;
      z-index: -1;
      background-color: #333;
      width: 40px;
      height: 40px;
      margin-left: -6px;
      border-radius: 4px;
    }

    li.pushy-link span {
      display: inline-block;
      position: absolute;
      left: 8px;
      top: 15px;
      float: right;
      color: #08c;
    }

    li.pushy-link {
      position: relative;
    }

    .cols.col-5.left-menu {
      width: 100%;
    }

    .navigation {
      background: #e12e21;
    }

    .first-menu {
      margin: 0;
      background: #2897c0;
    }

    .first-menu li {
      margin: 12px  0;
      border: 0;
      width: 100%;
      height: 50px;
      -webkit-transform: skew(0deg);
      -moz-transform: skew(0deg);
      -o-transform: skew(0deg);
      transform: skew(0deg);
    }

    .first-menu span {
      -webkit-transform: skew(0deg);
      -moz-transform: skew(0deg);
      -o-transform: skew(0deg);
      transform: skew(0deg);
    }

    .first-menu li a {
      font-size: 15px;
      line-height: 50px;
    }

    li.link-third,
    li.link-second {
      margin-top: -3px;
    }

    .second-menu {
      padding: 0;
      height: auto;
      margin: -8px 0;
    }

    .mark {
      font-size: 15px;
      margin-top: 0;
    }

    .second-menu li {
      float: none;
      display: block;
      text-align: center;
      border-bottom: 1px solid #ec675f;
      padding: 5px;
      margin: 5px 0;
      border-right: 0;
      line-height: 32px;
    }

    .second-menu span {
      top: -5px;
    }

    .content {
      width: 100%;
      margin: 0 auto;
      padding: 40px 10px;
    }

    .logo img {
      width: 40px;
    }

    .logo span {
      font-size: 15px;
      padding-left: 5px;
      margin-top: 3px;
    }

    .logo p {
      padding-left: 5px;
      font-size: 11px;
    }

    .col-7 {
      width: 100%;
    }

    .col-5 {
      width: 100%;
    }

    .rewiews-grid {
      position: absolute;
      left: 0;
      bottom: -25px;
    }
  }

  @media screen and (max-width: 345px) {
    .logo-grid {
      max-width: 150px;
      float: left;
      max-height: 40px;
    }

    .logo img {
      width: 30px;
    }

    .logo span {
      font-size: 14px;
      padding-left: 5px;
      margin-top: -2px;
    }

    .logo p {
      padding-left: 5px;
      font-size: 10px;
    }

    .catalog-item h3 {
      max-width: 100%;
      float: left;
      margin-right: 20px;
    }
  }




</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Рейтинг автосалонов Москвы</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= favicon_link_tag 'favicon.png' %>
    <!--<%= render 'layouts/embed_styles' %>-->
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'%>
    <%= javascript_include_tag 'modals', 'data-turbolinks-track': false %>
  </head>

  <body>
    <div id="modal-holder"></div>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= render 'blocks/header' %>
    <%= render 'blocks/menu' %>
    <div class="container">
      <%= yield %>
      <%= render 'blocks/footer' %>
    </div>
  </body>
</html>
<%= javascript_include_tag 'pushy', 'data-turbolinks-track': false %>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'%>

app/views/layouts/modal.slim
#mainModal.modal.fade aria-hidden="true" aria-labelledby="mainModalLabel" role="dialog" tabindex="-1"
  .modal-dialog
    .modal-content
      .modal-header
        button.close data-dismiss="modal" type="button"
          span aria-hidden="true"  ×
          span.sr-only Close
        h4#mainModalLabel.modal-title
          = yield :title if content_for? :title
          |
      = yield

app/views/pages/about.html.slim
.cols.col-12.main-page
  .content.clearfix
    .page
      .preview
        h1 О сайте
        | Наш сайт создан для того, чтобы представить вам свежую информацию по самым популярным столичным автосалонам и объективные отзывы клиентов, совершивших покупки в оных.

app/views/pages/contacts.html.slim
.cols.col-12.main-page
  .content.clearfix
    .page
      .preview
        h1 Свяжитесь с нами
        | Наш сайт создан для того, чтобы представить вам свежую информацию по самым популярным столичным автосалонам и объективные отзывы клиентов, совершивших покупки в оных.
        br/
        | Если у вас возникли вопросы, мы с радостью ответим на них. Оставляйте заявку в форме для обратной связи. В ближайшее время мы свяжемся с вами и ответим на все интересующие вас вопросы.
  =render 'feedbacks/form'